### ISSUE TITLE
Bug: numpad ENTER key doesn't work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#117]
Only the normal one in the middle of the keyboard works.
The one on the far right side doesn't do anything.

**Comment by rom1v** [comment]
Thank you for the report :+1:

I just fixed it on `master`.

**Comment by AndroidDeveloperLB** [comment]
@rom1v Thank you. I'm happy you understood what I meant.

**Comment by AndroidDeveloperLB** [comment]
I can still see this issue. It acts as space this time instead of enter.
Why is it closed?
In order to test, open Chrome, and on Google's website (not on the address bar), search for something using the small Enter key.

Tested on v1.8 , with Galaxy S7 , Android 8.0.0

**Comment by rom1v** [comment]
> I can still see this issue.

It's not the same issue.

> It acts as space this time instead of enter.

Indeed, even in the Firefox address bar. But in a text field, it correctly acts as "enter" (try in google.com for example).

Technically, it is correctly bound to [`KEYCODE_NUMPAD_ENTER`](https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_NUMPAD_ENTER):
https://github.com/Genymobile/scrcpy/blob/5d473efeb5c4f42a75aad6ab5892e2813358c0c9/app/src/convert.c#L80

By the way, it is the same behavior with:

    adb shell input keyevent KEYCODE_NUMPAD_ENTER

I don't know why Android considers `KEYCODE_NUMPAD_ENTER` as a space in some contexts…

**Comment by AndroidDeveloperLB** [comment]
I see. The reason I thought it's because of this tool, is that the callback of `setOnEditorActionListener` doesn't get called when I press the small Enter key.
I think it's a bug on Android itself, then, because there shouldn't be a difference between pressing on the large one and the small one...
No?

**Comment by AndroidDeveloperLB** [comment]
When running on emulator, it doesn't even put a space.
How odd. I've reported it here:
https://issuetracker.google.com/issues/134205188
