### ISSUE TITLE
Not working on ADB over network.

### ISSUE THREAD

**Issue by anisulislam** [Genymobile/scrcpy#146]
After following all the instructions, when I launch scrcpy.exe from CLI or GUI it does nothing. Literally nothing.

**Comment by rom1v** [comment]
Please try with current `master` branch (see https://github.com/Genymobile/scrcpy/issues/5#issuecomment-373721710).

**Comment by rom1v** [comment]
Should be fixed by v1.2. Please reopen otherwise.

**Comment by mayureshw** [comment]
Tried the prebuilt 1.2 jar from the home page. The issue still exists.

**Comment by rom1v** [comment]
And with v1.2 client? (not only the jar server)

**Comment by mayureshw** [comment]
On Thu, Jun 14, 2018 at 09:10:46AM -0700, Romain Vimont wrote:
>    And with v1.2 client? (not only the jar server)

Yes, cloned just today.

# scrcpy -v
scrcpy v1.2

Mayuresh

**Comment by mayureshw** [comment]
On Thu, Jun 14, 2018 at 09:10:46AM -0700, Romain Vimont wrote:
>    And with v1.2 client? (not only the jar server)

Further to confirming that in the last mail, sharing the error message.

# scrcpy 
87 KB/s (19342 bytes in 0.216s)
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
CRITICAL: Could not initialize SDL: No available video device

# adb devices
List of devices attached 
yu2:5555        device

Mayuresh

**Comment by rom1v** [comment]
OK. Could you build in debug mode, please, and copy the DEBUG logs when you attempt to connect over tcpip?

**Comment by rom1v** [comment]
OK. Could you compile in debug mode (without `--buildtype=release`) and see the DEBUG logs when you attempt to connect over tcpip, please?

**Comment by rom1v** [comment]
> CRITICAL: Could not initialize SDL: No available video device

It seems it is not related to adb over tcpip. Does it work over USB?

**Comment by mayureshw** [comment]
On Thu, Jun 14, 2018 at 10:13:39AM -0700, Romain Vimont wrote:
>      CRITICAL: Could not initialize SDL: No available video device
> 
>    It seems it is not related to adb over tcpip. Does it work over USB?

I am struggling with adb listing device over USB. Somehow it just doesn't
find the device. So constrained to tcpip only.

Will share debug output for tcpip.

Yes SDL error does not look related to this, but I guess we can come to it
after getting it working otherwise.

**Comment by mayureshw** [comment]
On Thu, Jun 14, 2018 at 10:12:22AM -0700, Romain Vimont wrote:
>    OK. Could you compile in debug mode (without --buildtype=release) and see
>    the DEBUG logs when you attempt to connect over tcpip, please?

DEBUG helped to know that it wasn't finding X11 libraries. Then I ran
as "LD_LIBRARY_PATH=/usr/X11R7/lib scrcpy" that error went away.

Now it is not finding several symbols. Errors are more or less like shown
here by someone:

https://ideone.com/TmAOsP

However, despite those errors I am able to see the screen! Not sure
whether I'll face any problems. Will report if any.

Thanks. It's a wonderful application.

**Comment by rom1v** [comment]
@mayureshw Similar to https://github.com/Genymobile/scrcpy/issues/17?

**Comment by mayureshw** [comment]
On Fri, Jun 15, 2018 at 12:36:00AM -0700, Romain Vimont wrote:
>    @mayureshw Similar to #17?

Looks like. May be the installation notes can make a note of this.

It can be closed.
