### ISSUE TITLE
Colors Washed out

### ISSUE THREAD

**Issue by jogadaexcelente** [Genymobile/scrcpy#1868]
Every time I run Scrcpy the colors on the screen seems to be washed out even my screen brightness is at the maximum. This screenshot is from the app itself. The box in the middle is supposed to be full white but it's kinda gray as if the brightness was low. Maybe it's something simple to fix but I couldn't find anything related on the issues page. Thanks!
![PRINT01](https://user-images.githubusercontent.com/64862877/97595608-9ea74e00-19e2-11eb-815a-0b706b2eda48.png)

**Comment by rom1v** [comment]
Is it the same with:
```bash
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
vlc file.mp4
```
?

**Comment by jamespharvey20** [comment]
I had this happen because of a blue light filter app.  In addition to filtering out a percentage of blue light to affect the color temperature, it allows dimming.  (I like using this, because even with Android dimmed to its lowest setting, I'd prefer it to be dimmer if I'm using it with the lights off, to not disturb my wife.)  The Android doesn't have these functions for it to use, so it has to simulate them by doing something like a transparent overlay on top.  So, when I first used scrcpy, it displayed as a different color temperature and dimmer, because the white pixels on the screen that it was copying were in fact not 100% white.

Our eyes adjust to what we perceive as the whitepoint.  If you've ever had an app like this, see if it's still running.  Even if looking at the actual phone looks like it's not affecting it.

**Comment by jogadaexcelente** [comment]
Well.. turns out the "problem" was on my phone. The same thing would happen when taking a screenshot. The screenshot itself would be darker than what was on the screen. While looking for a way to solve this, I came across a post on reddit saying that if you set your phone to automatic brightness this might happen. So I just unchecked this option, restarted the phone and it was solved. I'm on a Xiomi Mi9 SE by the way. At least now we know what to do in case this happens again. Thanks!

**Comment by SibiAkkash** [comment]
I noticed a quirk while watching Youtube. When I press the spacebar while watching a video, a grey overlay appears on the screen and on the phone as well. This effect vanishes when i close and reopen the video. 
I've attached a video here, you can see the screen greying out when i press the spacebar.

https://user-images.githubusercontent.com/39093537/132947979-9aaffe93-9927-4fbc-a757-1fea71201447.mp4

**Comment by jorgearenas-mfs** [comment]
I have noticed that the problem is due to dark mode being on at least in Xiaomi devices, the moment you turn off dark mode this it's solved

**Comment by AngeloTadeucci** [comment]
Can confirm it's an Xiaomi issue with dark mode, @rom1v is this possible to be fixed? If you are too busy and you can give me an direction of where I can find the issue in the code base I could try to fix it

**Comment by AngeloTadeucci** [comment]
> 
> No idea.
> 
> Does it also happen with screenrecord? [#1868 (comment)](https://github.com/Genymobile/scrcpy/issues/1868#issuecomment-719095574)

Yes, it does happen on recording.

https://github.com/Genymobile/scrcpy/assets/15664821/d34926e2-34d5-46d6-bb1d-64e4cf7980e1

**Comment by blackmatrixx** [comment]
> I have noticed that the problem is due to dark mode being on at least in Xiaomi devices, the moment you turn off dark mode this it's solved

This dark mode thing effects nothing to me any other fix?

**Comment by rom1v** [comment]
Does it still happen with scrcpy 2.5?

**Comment by arnoo** [comment]
I have the same issue with scrcpy 3.1. What looks white on my phone looks grey on the computer copy. In my case, screen recordings look OK, it's only with scrcpy that the issue occurs.
I have tried disabling adaptive lighting and visual comfort, I'm not using dark mode but just in case I tried switching it on and off... nothing changes.

**Comment by rom1v** [comment]
Which android version?

What about these commands:

```bash
scrcpy --video-codec-options=color-range=1
scrcpy --video-codec-options=color-range=2
```

?

And with another video encoder (see `scrcpy --list-encoders`)?

Refs #4756

**Comment by arnoo** [comment]
Android 12 (Samsung Galaxy S10e)

I tried other encoders, they all do the same thing. color-range options don't change anything either :-/

I also tried the following two as mentionned in the issue you referenced:

```
scrcpy --no-audio --video-codec-options=color-range=1 --render=driver=opengles2
scrcpy --no-audio --video-codec-options=color-range=1 --render=driver=software
```

**Comment by rom1v** [comment]
Wvat if you record (`scrcpy --record=file.mp4`) and play the resulting file with VLC (or Firefox).

**Comment by jogadaexcelente** [comment]
What solved for me was setting the Screen Mode to Natural under Screen
settings on the phone. If it's something else like Vivid for example the
colors might end up with this look on Scrcpy.

Em qui., 20 de fev. de 2025, 09:54, Arnaud Bétrémieux <
***@***.***> escreveu:

**Comment by arnoo** [comment]
> Wvat if you record (`scrcpy --record=file.mp4`) and play the resulting file with VLC (or Firefox).

When I do that, while recording, I see the issue, but when playing back with VLC, the colors look good ! So it would be an issue on the playback side.

**Comment by arnoo** [comment]
> What solved for me was setting the Screen Mode to Natural under Screen
> settings on the phone. If it's something else like Vivid for example the
> colors might end up with this look on Scrcpy.
> 
> Em qui., 20 de fev. de 2025, 09:54, Arnaud Bétrémieux <
> ***@***.***> escreveu:
> […](#)

I tried that, to no avail.

**Comment by rom1v** [comment]
> When I do that, while recording, I see the issue, but when playing back with VLC, the colors look good !

Please post the output of:

```bash
mediainfo file.mp4
```

**Comment by arnoo** [comment]
```
❯ mediainfo file.mp4 
General
Complete name                            : file.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 9.79 MiB
Duration                                 : 12 s 414 ms
Overall bit rate                         : 6 615 kb/s
Frame rate                               : 48.978 FPS
Writing application                      : Lavf61.7.100
Comment                                  : Recorded by scrcpy 3.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L5
Format settings                          : 1 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 12 s 414 ms
Bit rate                                 : 6 604 kb/s
Width                                    : 1 080 pixels
Height                                   : 2 280 pixels
Display aspect ratio                     : 0.474
Frame rate mode                          : Variable
Frame rate                               : 48.978 FPS
Minimum frame rate                       : 8.651 FPS
Maximum frame rate                       : 102.975 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.055
Stream size                              : 9.77 MiB (100%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC
```

**Comment by arnoo** [comment]
```
And it seems it happens with all render-drivers, it is correct:
```
I tried all the ones listed in the docs, except software, which gives me `CRITICAL: Could not create renderer: Couldn't find matching render driver`. They all have the same issue.

**Comment by szmarczak** [comment]
Nothing Phone 2 - Android 15. Screenshot colors are ok. The video is shit. Tried different codes, no change. Different color options, no change.

**Comment by szmarczak** [comment]
Recorded screen via Android and the colors are still shit. However it would be nice to somehow fix this via some setting.

**Comment by ryanbarillosofficial** [comment]
In my case, colors are way, _way_ more washed out on my Arch Linux install than on my Windows 11 install (both on my Samsung Note 9 & Google Pixel 7 phones).

It's as though contrast, vibrancy & saturation are reduced on Arch Linux 

This is my view on Arch Linux with scrcpy:

![Image](https://github.com/user-attachments/assets/c5eb6c75-1639-4abe-add0-b3a66dd9a37e)
![Image](https://github.com/user-attachments/assets/efb017b4-6e58-429c-a2e7-6a86b583622f)

And now this is my view on Windows 11, where colors are much more prominent:

![Image](https://github.com/user-attachments/assets/ffd7a126-4925-4720-9b5f-355814c48da0)
![Image](https://github.com/user-attachments/assets/55645930-f37f-492e-ba44-e249eaf1b6ca)
----
As for the device I'm using scrcpy (if ever relevant), it's a 2021 ASUS Zephyrus G14 with AMD + NVIDIA graphics card with AMD CPU.

And the mobile game in view of these screenshots is _Strategy & Tactics 2_

**Comment by randomwindstorm** [comment]
I've got the same problem on arch. Phone is a Pixel 5a and color settings already set to Natural.
It's especially noticeable on any app with an AMOLED black theme because the blacks become gray.

Screenshots with adb commands show the true black level and video recording through scrcpy show the true black level but the window itself desaturates the black level to gray with both opengl and software renderer.

ADB
![Image](https://github.com/user-attachments/assets/f9fcf623-b6a8-46e8-967e-4c3431413871)
Screenshot of rendered window
![Image](https://github.com/user-attachments/assets/8679ccef-1c33-4c23-8f12-5aaad4d35b9d)

**Comment by rom1v** [comment]
Please test #6216 (especially 4c4ce59db54e6e50968d7ba3b379b8d597b2e02d).

**Comment by binarynoise** [comment]
The PR solves the issue. Black is now displayed as black and not as gray. 👍

**Comment by rom1v** [comment]
Great 👍 

Also, if you cherry-pick only this commit onto `master`: 4c4ce59db54e6e50968d7ba3b379b8d597b2e02d, does it also solve the issue? (if you know how to, otherwise I can provide a binary)

**Comment by binarynoise** [comment]
Unfortunately I run into merge conflicts on cherry-picking. Do we have a better base?

**Comment by rom1v** [comment]
Sorry, don't cherry-pick (you need the commits before), so just checkout it.

Better: the same in a more recent version: checkout d7e0d36fe6a95e49ba3dceba1f550d746fbfc30b.

**Comment by binarynoise** [comment]
the commit that does the trick is 77cd5d9aef6774e3509789a1069aec1db5c6b5d4 (according to my bisect), so d7e0d36fe6a95e49ba3dceba1f550d746fbfc30b is not enough.

**Comment by rom1v** [comment]
OK, thank you 👍 So this is fixed by SDL3.

**Comment by randomwindstorm** [comment]
So unfortunately I tried the [actions build from the PR](https://github.com/rom1v/scrcpy/actions/runs/16226120027) and the colors are still washed out.

I have sdl3 package installed from arch repo, and I also installed sdl3-compat just in case that was the problem.

Any suggestions?

EDIT: I looked at the log for the [build-linux-x86_64](https://github.com/rom1v/scrcpy/actions/runs/16226120027/job/45818320800#logs) action and it shows it installed libsdl2-2.0-0 and libsdl2-dev on line 101 under the Install Dependencies step. Maybe this was the problem?

<img width="1461" height="867" alt="Image" src="https://github.com/user-attachments/assets/cd817cc0-e493-4b2d-b018-4fc7813e2b8d" />

**Comment by dddddjent** [comment]
I use archlinux+waydroid and with the latest SDL3 branch I still have the problem. I'm on AMD igpu+Nvidia dgpu
Below is the comparison of the output. The upper is the output video from scrcpy --record out.mp4. Below is the direct output.
<img width="308" height="294" alt="Image" src="https://github.com/user-attachments/assets/4503260d-1324-40ce-bb25-0e41f8108e65" />

Below is the build output. I believe I used SDL3 correctly?
```
 meson setup x --buildtype=release --strip -Db_lto=true
The Meson build system
Version: 1.9.0
Source dir: /home/ljl/Documents/cache/scrcpy
Build dir: /home/ljl/Documents/cache/scrcpy/x
Build type: native build
Project name: scrcpy
Project version: 3.3.2
C compiler for the host machine: cc (gcc 15.2.1 "cc (GCC) 15.2.1 20250813")
C linker for the host machine: cc ld.bfd 2.45.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.5.1
Run-time dependency libavformat found: YES 61.7.100
Run-time dependency libavcodec found: YES 61.19.101
Run-time dependency libavutil found: YES 59.39.100
Run-time dependency libswresample found: YES 5.3.100
Run-time dependency sdl3 found: YES 3.2.22
Run-time dependency libavdevice found: YES 61.3.100
Run-time dependency libusb-1.0 found: YES 1.0.29
Checking for function "strdup" : YES
Checking for function "asprintf" : YES
Checking for function "vasprintf" : YES
Checking for function "nrand48" : YES
Checking for function "jrand48" : YES
Checking for function "reallocarray" : YES
Header "sys/socket.h" has symbol "SOCK_CLOEXEC" : YES
Configuring config.h using configuration
Program ./scripts/build-wrapper.sh found: YES (/home/ljl/Documents/cache/scrcpy/server/./scripts/build-wrapper.sh)
Build targets in project: 2

scrcpy 3.3.2

  User defined options
    b_lto    : true
    buildtype: release
    strip    : true

Found ninja-1.12.1 at /usr/bin/ninja

ninja -Cx
ninja: Entering directory `x'
[50/77] Generating server/scrcpy-server with a custom command

BUILD SUCCESSFUL in 409ms
44 actionable tasks: 1 executed, 43 up-to-date
[77/77] Linking target app/scrcpy
```

**Comment by rom1v** [comment]
> I use archlinux+waydroid and with the latest SDL3 branch I still have the problem.

It probably depends on the backend used in SDL3.

Try with different values for `--render-driver=xxx` (`opengl`, `opengles2`, `vulkan`, `gpu`…): https://wiki.libsdl.org/SDL3/SDL_HINT_RENDER_DRIVER

**Comment by dddddjent** [comment]
I kind of solved the problem using AI. https://github.com/dddddjent/scrcpy/tree/sdl3. It seems like when the colorspace is not specified, there could be a better default colorspace.

**Comment by rom1v** [comment]
> I kind of solved the problem using AI. https://github.com/dddddjent/scrcpy/tree/sdl3. It seems like when the colorspace is not specified, there could be a better default colorspace.

Interesting. Can you confirm that your fix works both when `is_hd` is `true` or `false`:

```bash
scrcpy          # implies is_hd = true
scrcpy -m600    # implies is_hd = false
```

**Comment by dddddjent** [comment]
<img width="1500" height="335" alt="Image" src="https://github.com/user-attachments/assets/97df0836-2a3b-4a5e-bf38-a8f0792b5c14" />

The black is correct. There's still some color bias with that yellow.

**Comment by rom1v** [comment]
And if you force `is_hd = true` [here](https://github.com/dddddjent/scrcpy/commit/280f033b054c655575f9ef28392fc6fd6faf2162#diff-7218c52a7f04778d32198290200b433e664025713c3efaceb8655bd04a99aa47R149), does it work better even with `scrcpy -m600`?

**Comment by dddddjent** [comment]
<img width="203" height="322" alt="Image" src="https://github.com/user-attachments/assets/ffc7b10b-256d-47fe-b12e-bd6ca984df1d" />
Now they are the same. I commented out everything except the first return. It seems like BT709 is always the correct one.

**Comment by dddddjent** [comment]
https://github.com/dddddjent/scrcpy/commit/280f033b054c655575f9ef28392fc6fd6faf2162#diff-7218c52a7f04778d32198290200b433e664025713c3efaceb8655bd04a99aa47L144
And I can also confirm that with only the change here the output color is correct. No need to change SDL_PIXELFORMA

**Comment by rom1v** [comment]
What is the value of `color_space` in your case [here](https://github.com/dddddjent/scrcpy/commit/280f033b054c655575f9ef28392fc6fd6faf2162#diff-7218c52a7f04778d32198290200b433e664025713c3efaceb8655bd04a99aa47R129-R133)?

Is it `AVCOL_SPC_UNSPECIFIED` or something else?

**Comment by dddddjent** [comment]
AVCOL_SPC_RGB this

**Comment by rom1v** [comment]
@dddddjent Then I think the correct fix is:

```diff
diff --git app/src/display.c app/src/display.c
index 361cfbf15..663c6d829 100644
--- app/src/display.c
+++ app/src/display.c
@@ -141,6 +141,8 @@ sc_display_to_sdl_color_space(enum AVColorSpace color_space,
         case AVCOL_SPC_BT2020_CL:
             return full_range ? SDL_COLORSPACE_BT2020_FULL
                               : SDL_COLORSPACE_BT2020_LIMITED;
+        case AVCOL_SPC_RGB:
+            return SDL_COLORSPACE_SRGB;
         default:
             return SDL_COLORSPACE_JPEG;
     }
```

Please remove your changes and apply this diff.

**Comment by dddddjent** [comment]
case AVCOL_SPC_RGB:
            return SDL_COLORSPACE_BT709_LIMITED;
I need to use this. If I use srgb, the GUI will not show up. And if BT709 is not limited, the color is incorrect like before

**Comment by rom1v** [comment]
OK, weird.

Maybe this diff then (to take into account the value of `full_range`):

```diff
diff --git app/src/display.c app/src/display.c
index 361cfbf15..50500f19e 100644
--- app/src/display.c
+++ app/src/display.c
@@ -131,6 +131,7 @@ sc_display_to_sdl_color_space(enum AVColorSpace color_space,
 
     switch (color_space) {
         case AVCOL_SPC_BT709:
+        case AVCOL_SPC_RGB:
             return full_range ? SDL_COLORSPACE_BT709_FULL
                               : SDL_COLORSPACE_BT709_LIMITED;
         case AVCOL_SPC_BT470BG:
```

**Comment by dddddjent** [comment]
This works. The color_range is AVCOL_RANGE_MPEG

**Comment by rom1v** [comment]
Thanks, I included the fix (76352d3d6c4d4668e8bfed85a4cc19c57a2c621a) on the `sdl3` branch.

**Comment by dddddjent** [comment]
Is it possible to also fix this on master SDL2?
