### ISSUE TITLE
Can't find scrcpy in homebrew

### ISSUE THREAD

**Issue by EvatsugDnalloR** [Genymobile/scrcpy#2423]
I've once succesfully installed scrcpy on big sur but now i went back to Catalina 10.15.7, and it just simply can't find scrcpy via brew install:
brew install -- scrcpy
fatal: Could not resolve HEAD to a revision
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "scrcpy".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
And i've already installed android platform tools succesfully so i don't think it's the problem of homebrew, but i just can't understand it...

**Comment by rom1v** [comment]
#2247 ?

**Comment by EvatsugDnalloR** [comment]
> I have this problem too.
> 
> *edit : solved with this command : Tapping homebrew/core

Thanks man, but now i'm back to Big Sur and the brew install command works

**Comment by EvatsugDnalloR** [comment]
> I'm having the same issue now and the `Tapping homebrew/core` command doesn't work for me. it says tapping command not found. how did you do it?

I upgrated to Big Sur and it has been solved... so i'm quite sure that it's the problem of Catalina...

**Comment by IAproject21** [comment]
Hi, i am actually on Big Sur but I still have the problem. Can someone help? thanks.
