### ISSUE TITLE
Make available resources about building/using newer versions with Meizu phones

### ISSUE THREAD

**Issue by Daniel-Brum** [Genymobile/scrcpy#2656]
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I can't seem to make scrcpy work with my Meizu M6 Note phone whenever I use any version above 1.13. I've seen in another issue that the "culprit commit" was identified and that it did pose other problems, so I can understand it might be needed.
But there are some changes and new features that are present in newer versions that are pretty much inaccessible on some setups for that reason.

**Describe the solution you'd like**
However, if it's possible, I'd like to see an alternative to the phones that don't work with the change introduced in 1.14 and above. It doesn't even need to be prebuilt; having written resources about how to do it would be enough.

**Describe alternatives you've considered**
I've tried all the workarounds I've found in all related issues (like changing bitrate, encoder and even cables/ports). But none of them worked on newer versions.

**Comment by rom1v** [comment]
> I've seen in another issue that the "culprit commit" was identified and that it did pose other problems, so I can understand it might be needed.

I'm pretty sure we can make it work nevertheless, but I have no Meizu device.

Could you please help by testing this: https://github.com/Genymobile/scrcpy/issues/240

Otherwise, building steps are described here: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md

**Comment by rom1v** [comment]
> I've seen in another issue that the "culprit commit" was identified and that it did pose other problems, so I can understand it might be needed.

I'm pretty sure we can make it work nevertheless, but I have no Meizu device.

Could you please help by testing this: https://github.com/Genymobile/scrcpy/issues/240#issuecomment-703829170

Otherwise, building steps are described here: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md

**Comment by Daniel-Brum** [comment]
Following the instructions in [240-comment](https://github.com/Genymobile/scrcpy/issues/240#issuecomment-703829170), I get the same "freezing" problem, but there's no message displayed after 
```[server] INFO: Device: Meizu M6 Note (Android 7.1.2)
[server] INFO: ### 1
[server] INFO: ### 2
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920```

Are there any logs I can try to get and paste here? If so, how can I do it?

**Comment by rom1v** [comment]
Please replace the server from v1.19 release by this one:
[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2656/1/scrcpy-server) _sha256:4587ff4a115ca535cb6bf249cb09add2005e650e177b4335281e2d2df731d39d_

Does it freeze? Please post the whole console output.

<details><summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index 2f7109c5..df73d60a 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -9,6 +9,7 @@ import android.media.MediaCodecList;
 import android.media.MediaFormat;
 import android.os.Build;
 import android.os.IBinder;
+import android.os.Looper;
 import android.view.Surface;
 
 import java.io.FileDescriptor;
@@ -55,7 +56,10 @@ public class ScreenEncoder implements Device.RotationListener {
     }
 
     public void streamScreen(Device device, FileDescriptor fd) throws IOException {
-        Workarounds.prepareMainLooper();
+        Ln.i("Manufacturer: [" + Build.MANUFACTURER + "]");
+        Ln.i("Brand: [" + Build.BRAND + "]");
+        Ln.i("Model: [" + Build.MODEL + "]");
+        Looper.prepare();
 
         try {
             internalStreamScreen(device, fd);
```

</details>

**Comment by Daniel-Brum** [comment]
I get this:

```
[server] INFO: Device: Meizu M6 Note (Android 7.1.2)
[server] INFO: Manufacturer: [Meizu]
[server] INFO: Brand: [Meizu]
[server] INFO: Model: [M6 Note]
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
```

and then nothing happens. Anything else I could try?

**Comment by rom1v** [comment]
And this one?

[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2656/1/scrcpy-server) _sha256:971189967483880579dfb428ceb0e16e401592f931efa605446e167c3776b6f8_

<details><summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index 2f7109c5..ec9330bb 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -56,6 +56,9 @@ public class ScreenEncoder implements Device.RotationListener {
 
     public void streamScreen(Device device, FileDescriptor fd) throws IOException {
         Workarounds.prepareMainLooper();
+        if (Build.BRAND.equalsIgnoreCase("meizu")) {
+            Workarounds.fillAppInfo();
+        }
 
         try {
             internalStreamScreen(device, fd);
```

</details>

**Comment by Daniel-Brum** [comment]
```
[server] INFO: Device: Meizu M6 Note (Android 7.1.2)
[server] INFO: Manufacturer: [Meizu]
[server] INFO: Brand: [Meizu]
[server] INFO: Model: [M6 Note]
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
```

I've yet to try the encoder options though, but for now, no success.

**Comment by rom1v** [comment]
Oops, the last link was incorrect (it was the same as the first one). I fixed it. Could you retry, please?

**Comment by Daniel-Brum** [comment]
It worked! Thanks a lot!

I still have to check the new features (I got really attracted by the --max-fps option), but so far it's working fine.

**Comment by rom1v** [comment]
Fixed on `dev`: 8df42cec82cb5856e6c10a4089e6b2953310da6e

Just to be sure, could you test the final version:
[`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2656/3/scrcpy-server) _sha256:7f2d14cf95ff3c490d6402100bf8f04261a5bc9bc050dfff83e6ee48ec5ac5d6_

**Comment by Daniel-Brum** [comment]
It worked fine too. Would be nice having this server file "pinned" or something like that, if possible. Thanks a lot for your help!

**Comment by rom1v** [comment]
> Would be nice having this server file "pinned" or something like that

What do you mean?

**Comment by Daniel-Brum** [comment]
Pinned is not the correct word for it, I suppose, but it would be nice to have the "alternative server" someplace easier to come by (though the ones who need it will probably search for it anyways, so not having that isn't a problem), Somewhere like in the Releases page for each version? Only if it isn't troublesome, of course.

**Comment by rom1v** [comment]
The problem is fixed on `dev` branch, so the next release will work as expected.

It was just a "bug" like many others, there are no backports to older versions.

**Comment by rom1v** [comment]
@veselcraft Please test https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468897171. Does it work?

**Comment by veselcraft** [comment]
> @veselcraft Please test [#3801 (comment)](https://github.com/Genymobile/scrcpy/issues/3801#issuecomment-1468897171). Does it work?

Sure it does! It's smooth and the mouse controls works perfectly.

But i still have some glitches here, i think this is a problem on Flyme's side, not on scrcpy. Thanks for the fix anyways!
![image](https://user-images.githubusercontent.com/22993408/236582342-67e9ad09-b886-4c79-97c4-37110400ee74.png)
![image](https://user-images.githubusercontent.com/22993408/236582507-37dcaf6b-cfec-436c-89e8-0ebccbcf3fda.png)

**Comment by rom1v** [comment]
If you record with `adb shell screenrecord /sdcard/file.mp4`, is the problem present on the resulting file?

**Comment by veselcraft** [comment]
> If you record with `adb shell screenrecord /sdcard/file.mp4`, is the problem present on the resulting file?

It's present in any third-party screen recorder
