### ISSUE TITLE
Using -K breaks the display output

### ISSUE THREAD

**Issue by bloopiy** [Genymobile/scrcpy#5691]
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** WIndows
 - **Scrcpy version:** [e.g. 2.5]
 - **Installation method:** Windowns release
 - **Device model:** Samsung S24 Ultra (SM-S928B)
 - **Android version:** 14

## Describe the bug

Using the -K parameter breaks the output of the screen displayed on the computer. 

```

```
First screenshot is ```scrcpy``` and second screenshot is ```scrcpy -K```
![Screenshot 2024-12-20 123315](https://github.com/user-attachments/assets/e0e0b40a-ab98-4da3-93aa-e3280b4e9349)

![Screenshot 2024-12-20 123341](https://github.com/user-attachments/assets/a03559df-a999-451c-89bc-9956ecaaaec0)

**Comment by rom1v** [comment]
Are you sure this is related to `-K`? It looks like an unrelated (random) capture issue.

Is it solved by pressing <kbd>Alt</kbd>+<kbd>r</kbd>?

**Comment by bloopiy** [comment]
Yes I'm sure, works fine with any other arguments. I tested multiple times. No it's not solved it Alt + r. It temporarily fixes itself only to revert back to the broken output. It's weird that -K does it so I checked multiple times. 

https://github.com/user-attachments/assets/105cd98e-f7ac-4df3-b4d9-5731516c510e

**Comment by rom1v** [comment]
I have the same problem on a Galaxy Tab A8. Indeed, `-K` makes the problem occur immediately (I had never noticed).

However, <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>r</kbd> fixes it (it's not <kbd>Alt</kbd>+<kbd>r</kbd> as I said earlier). It seems there is a race condition between size changes and capture on these Samsung devices. :confused:

**Comment by bloopiy** [comment]
WIll this be fixed on scrcpy or is still considered a ROM bug?

**Comment by skylai82** [comment]
Temporary solution! 👍  :)
[scrcpy-win64-v3.1(Solve -K).zip](https://github.com/user-attachments/files/18549226/scrcpy-win64-v3.1.Solve.-K.zip)

![Image](https://github.com/user-attachments/assets/a7609515-8be8-4035-ac93-f65dfe160de6)
SCRCPY USB
↓
delay 4sec
↓
autokey ctrl+shift+r 
↓
Video capture reset
![Image](https://github.com/user-attachments/assets/2efcf8a4-b643-47a9-a088-e56c8406a7e8)

**Comment by skylai82** [comment]
**[May be Solve for you too, for my Redmi Note 12 pro plus 5G is solved]**

1)Check your phone screen resolution &  Smallest width 395 dp
![Image](https://github.com/user-attachments/assets/89040202-cf57-4d4d-a739-7eab132470d2)
![Image](https://github.com/user-attachments/assets/0db74a07-661b-46fd-9772-156db8f63339)

2)Check your lancher Package name
![Image](https://github.com/user-attachments/assets/da843afc-653d-4681-a4eb-be0b973d91ff)
![Image](https://github.com/user-attachments/assets/4efd8392-9f5e-4722-979e-b40ffdb6690e)

![Image](https://github.com/user-attachments/assets/c025480c-a6f1-4c82-b6d2-2945edf3d796)

![Image](https://github.com/user-attachments/assets/aed2e0f2-f6f2-4c18-b248-72c12f543596)

3)Open CMD run your code _"1080x2400/395" change to your phone display  spec._ & `"com.miui.home" change to your launcher paskage name`
scrcpy -K -b 2M --shortcut-mod=lctrl,rctrl,lalt,ralt,lsuper,rsuper --new-display=1080x2400/395  --start-app=com.miui.home
scrcpy -K -b 2M --shortcut-mod=lctrl,rctrl,lalt,ralt,lsuper,rsuper --new-display=1080x2400/395  --start-app=android.miui.home.launcher.res

4)Result is blank screen , just ignore ite. Close it & run normal scrcpy -K.

![Image](https://github.com/user-attachments/assets/61bb33e9-b72e-4520-a780-8ab55172978c)
