### ISSUE TITLE
The Scrcpy version 3.3.1 pastes the crash window.

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#6224]
The Scrcpy version 3.3.1 pastes the crash window,This issue did not occur in Scrcpy version 3.2, and text can be pasted normally.

The following is the error log:
```
[server] INFO: Device: [samsung] KDDI SCV42 (Android 11)
INFO: Renderer: direct3d
INFO: Texture: 1920x1080
[server] ERROR: Exception on thread Thread[control-recv,5,main]
Wjava.lang.SecurityException: Given calling package android does not match caller's uid 2000A
R       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)N
:       at android.os.Parcel.createException(Parcel.java:2369)
D       at android.os.Parcel.readException(Parcel.java:2352)e
v       at android.os.Parcel.readException(Parcel.java:2294)i
c       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6663)e disconnected

        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7643)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3071)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2468)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2758)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2920)
        at android.provider.Settings$System.getStringForUser(Settings.java:3404)
        at android.provider.Settings$System.getIntForUser(Settings.java:3503)
        at android.provider.Settings$System.getInt(Settings.java:3497)
        at com.samsung.android.emergencymode.SemEmergencyManager.getModeType(SemEmergencyManager.java:343)
        at com.samsung.android.content.clipboard.SemClipboardManager.isUPSMode(SemClipboardManager.java:1641)
        at com.samsung.android.content.clipboard.SemClipboardManager.isEnabled(SemClipboardManager.java:1039)
        at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:132)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:36)
        at com.genymobile.scrcpy.device.Device.setClipboardText(Device.java:128)
        at com.genymobile.scrcpy.control.Controller.setClipboard(Controller.java:595)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:306)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:219)
        at com.genymobile.scrcpy.control.Controller.lambda$start$1$com-genymobile-scrcpy-control-Controller(Controller.java:227)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9503)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2831)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3617)
        at android.os.Binder.execTransactInternal(Binder.java:1190)
        at android.os.Binder.execTransact(Binder.java:1159)
```

**Comment by rom1v** [comment]
Probably 8a02e3c2f58cffc3fdd8c08b26aae04bbf9d5a97

**Comment by Helaer** [comment]
> 可能是 [8a02e3c](https://github.com/Genymobile/scrcpy/commit/8a02e3c2f58cffc3fdd8c08b26aae04bbf9d5a97)

@rom1v Can't this problem be fixed?

**Comment by Helaer** [comment]
> Probably [8a02e3c](https://github.com/Genymobile/scrcpy/commit/8a02e3c2f58cffc3fdd8c08b26aae04bbf9d5a97)

It was this change that caused it. I tried to restore all the changes to version 3.2 code, and it worked fine.

**Comment by Helaer** [comment]
> Probably [8a02e3c](https://github.com/Genymobile/scrcpy/commit/8a02e3c2f58cffc3fdd8c08b26aae04bbf9d5a97)

@rom1v  Will the subsequent new versions revert to the previous version (scrcpy3.2) with code changes? I encountered the problem of the pasting window crashing on several different models of mobile phones. When I restored this code to version 3.2 on scrcpy3.3.1 and rebuilt it, it worked normally on all these models.

**Comment by rom1v** [comment]
> on several different models of mobile phone

Which ones?

Maybe there's another way to avoid the error while still using the SDK ClipboardManager. What do you think @yume-chan?

**Comment by Helaer** [comment]
> > 在几种不同型号的手机上
> 
> 哪些？
> 
> 也许还有另一种方法可以避免错误，同时仍然使用 SDK ClipboardManager。你怎么看？

Most of them are Samsung models, including S10, S10+ and S9.

**Comment by yume-chan** [comment]
On Samsung Android 10:

```java
    public void setPrimaryClip(ClipData clip) {
        try {
            Preconditions.checkNotNull(clip);
            clip.prepareToLeaveProcess(true);
            this.mService.setPrimaryClip(clip, this.mContext.getOpPackageName(), this.mContext.getUserId());
            if (getSemClipboardManager().isEnabled()) {
                int callingUid = Binder.getCallingUid();
                int userId = UserHandle.getUserId(callingUid);
                if (this.mServiceEx != null) {
                    this.mServiceEx.addClip(clip, this.mContext.getOpPackageName(), userId);
                }
            }
        } catch (RemoteException e) {
            throw e.rethrowFromSystemServer();
        }
    }

    private SemClipboardManager getSemClipboardManager() {
        if (this.mSemClipboardManager == null) {
            this.mSemClipboardManager = (SemClipboardManager) this.mContext.getSystemService(Context.SEM_CLIPBOARD_SERVICE);
        }
        return this.mSemClipboardManager;
    }
```

So this should be enough:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/FakeContext.java b/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
index b43e9e1b..4f885681 100644
--- a/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
+++ b/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
@@ -5,7 +5,6 @@ import com.genymobile.scrcpy.wrappers.ServiceManager;
 import android.annotation.SuppressLint;
 import android.annotation.TargetApi;
 import android.content.AttributionSource;
-import android.content.ClipboardManager;
 import android.content.ContentResolver;
 import android.content.Context;
 import android.content.ContextWrapper;
@@ -20,6 +19,8 @@ public final class FakeContext extends ContextWrapper {
     public static final String PACKAGE_NAME = "com.android.shell";
     public static final int ROOT_UID = 0; // Like android.os.Process.ROOT_UID, but before API 29

+    public static final String SEM_CLIPBOARD_SERVICE = "semclipboard";
+
     private static final FakeContext INSTANCE = new FakeContext();

     public static FakeContext get() {
@@ -104,9 +105,9 @@ public final class FakeContext extends ContextWrapper {
             return null;
         }

-        if (Context.CLIPBOARD_SERVICE.equals(name)) {
+        if (Context.CLIPBOARD_SERVICE.equals(name) || SEM_CLIPBOARD_SERVICE.equals(name)) {
             try {
-                Field field = ClipboardManager.class.getDeclaredField("mContext");
+                Field field = service.getClass().getDeclaredField("mContext");
                 field.setAccessible(true);
                 field.set(service, this);
             } catch (ReflectiveOperationException e) {
```

---

Maybe we can blindly patch every `mContext` field.

Or patch fields on `Workarounds.getSystemContext()` instead of creating a `ContextWrapper`, so all services are created using the patched values

**Comment by yume-chan** [comment]
> So this should be enough:

This is not enough, because `SemEmergencyManager` called `Context.createPackageContext` so our `FakeContext` is not used.

```java
    public static SemEmergencyManager getInstance(Context context) {
        SemEmergencyManager semEmergencyManager;
        if (context == null) {
            return null;
        }
        synchronized (mLock) {
            if (sInstance == null) {
                Context ctx = null;
                try {
                    ctx = context.createPackageContext("android", 2);
                } catch (Exception e) {
                    Elog.d(TAG, "NameNotFoundException or SecurityException createPackageContext failed");
                    e.printStackTrace();
                }
                if (ctx != null) {
                    Elog.d(TAG, "android createPackageContext successful: " + ctx.getPackageName());
                } else {
                    ctx = context;y
                    Elog.d(TAG, "android createPackageContext null");
                }
                Handler handler = new Handler(ctx.getMainLooper());
                sInstance = new SemEmergencyManager(handler, ctx);
            }
            semEmergencyManager = sInstance;
        }
        return semEmergencyManager;
    }
```

Can still be workarounded:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/FakeContext.java b/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
index 0be0ba6c..e05b2a19 100644
--- a/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
+++ b/server/src/main/java/com/genymobile/scrcpy/FakeContext.java
@@ -99,6 +99,11 @@ public final class FakeContext extends ContextWrapper {
         return contentResolver;
     }

+    @Override
+    public Context createPackageContext(String packageName, int flags) throws PackageManager.NameNotFoundException {
+        return this;
+    }
+
     @SuppressLint("SoonBlockedPrivateApi")
     @Override
     public Object getSystemService(String name) {
```

I want to try creating a real `ContextImpl` with shell package name and etc.

**Comment by yume-chan** [comment]
In fact it crashes after `this.mService.setPrimaryClip()`, so the device clipboard has been updated, we can just ignore the exception.

**Comment by rom1v** [comment]
> In fact it crashes after `this.mService.setPrimaryClip()`, so the device clipboard has been updated, we can just ignore the exception.

Or apply a workaround so that `getSemClipboardManager().isEnabled()` returns `false`?

**Comment by yume-chan** [comment]
Add a try-catch around

https://github.com/Genymobile/scrcpy/blob/772f42134a327eea60955463d0ee8bb712168dd0/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L36

and ignore `SecurityException` from it

---

@Helaer can you check when you press <kbd>Ctrl</kbd> + <kbd>V</kbd>, although Scrcpy crashed, has the clipboard on device been updated (by pasting on devices directly)?

**Comment by rom1v** [comment]
> Add a try-catch around […] and ignore SecurityException from it

I'm not keen to just ignore any `SecurityException`, we want to ignore only those that originate from that Samsung-modified ROM. Otherwise, in the future, we'll have reports that clipboard is broken without any exception.

>         at com.samsung.android.content.clipboard.SemClipboardManager.isEnabled(SemClipboardManager.java:1039)
>         at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:132)

Do you have the code of `isEnabled()`? (or a framework.jar for this device?)

**Comment by yume-chan** [comment]
I only have one for Android 10, not Android 11 as reported.

[framework (samsung 10).zip](https://github.com/user-attachments/files/21254773/framework.samsung.10.zip)

**Comment by Helaer** [comment]
> 在
> 
> [scrcpy/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java](https://github.com/Genymobile/scrcpy/blob/772f42134a327eea60955463d0ee8bb712168dd0/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L36)
> 
> 36 号线 在[772F421](/Genymobile/scrcpy/commit/772f42134a327eea60955463d0ee8bb712168dd0)
> 
>  经理。setPrimaryClip（剪辑数据); 
> 并忽略它`SecurityException`
> 
> 您能否检查一下按 + 时，虽然 Scrcpy 崩溃了，但设备上的剪贴板是否已更新（通过直接粘贴到设备上）？CtrlV

Yes, after the window crashed, the phone's clipboard was updated and the text was pasted into the text box.

**Comment by Helaer** [comment]
> I only have one for Android 10, not Android 11 as reported.
> 
> [framework (samsung 10).zip](https://github.com/user-attachments/files/21254773/framework.samsung.10.zip)
@rom1v  @yume-chan 
[framework (samsungS10 Android 11).zip](https://github.com/user-attachments/files/21255200/framework.samsungS10.Android.11.zip)

**Comment by rom1v** [comment]
In the end, this `SecurityException: Given calling package android does not match caller's uid 2000` always come from reading or writing the settings.

This is the reason I changed the way scrcpy itself access the settings: cc0902b13c87fc98b1ed90b0700cc53ac4d7ee3c.

**Comment by rom1v** [comment]
> This is the reason I changed the way scrcpy itself access the settings: cc0902b13c87fc98b1ed90b0700cc53ac4d7ee3c.

In fact, what I said is obsolete since 91373d906b100349de959f49172d4605f66f64b2.

@Helaer Btw, could you confirm that you can run `scrcpy --show-touches` (for instance) with this diff on `dev` branch on your Samsung devices (where clipboard fails):

<details><summary>diff</summary>

```diff
diff --git server/src/main/java/com/genymobile/scrcpy/util/Settings.java server/src/main/java/com/genymobile/scrcpy/util/Settings.java
index e6465525a..4eb67d186 100644
--- server/src/main/java/com/genymobile/scrcpy/util/Settings.java
+++ server/src/main/java/com/genymobile/scrcpy/util/Settings.java
@@ -1,13 +1,8 @@
 package com.genymobile.scrcpy.util;
 
-import com.genymobile.scrcpy.AndroidVersions;
 import com.genymobile.scrcpy.wrappers.ContentProvider;
 import com.genymobile.scrcpy.wrappers.ServiceManager;
 
-import android.os.Build;
-
-import java.io.IOException;
-
 public final class Settings {
 
     public static final String TABLE_SYSTEM = ContentProvider.TABLE_SYSTEM;
@@ -18,66 +13,26 @@ public final class Settings {
         /* not instantiable */
     }
 
-    private static void execSettingsPut(String table, String key, String value) throws SettingsException {
-        try {
-            Command.exec("settings", "put", table, key, value);
-        } catch (IOException | InterruptedException e) {
-            throw new SettingsException("put", table, key, value, e);
-        }
-    }
-
-    private static String execSettingsGet(String table, String key) throws SettingsException {
-        try {
-            return Command.execReadLine("settings", "get", table, key);
-        } catch (IOException | InterruptedException e) {
-            throw new SettingsException("get", table, key, null, e);
-        }
-    }
-
     public static String getValue(String table, String key) throws SettingsException {
-        if (Build.VERSION.SDK_INT <= AndroidVersions.API_30_ANDROID_11) {
-            // on Android >= 12, it always fails: <https://github.com/Genymobile/scrcpy/issues/2788>
-            try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
-                return provider.getValue(table, key);
-            } catch (SettingsException e) {
-                Ln.w("Could not get settings value via ContentProvider, fallback to settings process", e);
-            }
+        try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
+            return provider.getValue(table, key);
         }
-
-        return execSettingsGet(table, key);
     }
 
     public static void putValue(String table, String key, String value) throws SettingsException {
-        if (Build.VERSION.SDK_INT <= AndroidVersions.API_30_ANDROID_11) {
-            // on Android >= 12, it always fails: <https://github.com/Genymobile/scrcpy/issues/2788>
-            try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
-                provider.putValue(table, key, value);
-            } catch (SettingsException e) {
-                Ln.w("Could not put settings value via ContentProvider, fallback to settings process", e);
-            }
+        try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
+            provider.putValue(table, key, value);
         }
 
-        execSettingsPut(table, key, value);
     }
 
     public static String getAndPutValue(String table, String key, String value) throws SettingsException {
-        if (Build.VERSION.SDK_INT <= AndroidVersions.API_30_ANDROID_11) {
-            // on Android >= 12, it always fails: <https://github.com/Genymobile/scrcpy/issues/2788>
-            try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
-                String oldValue = provider.getValue(table, key);
-                if (!value.equals(oldValue)) {
-                    provider.putValue(table, key, value);
-                }
-                return oldValue;
-            } catch (SettingsException e) {
-                Ln.w("Could not get and put settings value via ContentProvider, fallback to settings process", e);
+        try (ContentProvider provider = ServiceManager.getActivityManager().createSettingsProvider()) {
+            String oldValue = provider.getValue(table, key);
+            if (!value.equals(oldValue)) {
+                provider.putValue(table, key, value);
             }
+            return oldValue;
         }
-
-        String oldValue = getValue(table, key);
-        if (!value.equals(oldValue)) {
-            putValue(table, key, value);
-        }
-        return oldValue;
     }
 }
```

</details>

**Comment by Helaer** [comment]
> > This is the reason I changed the way scrcpy itself access the settings: [cc0902b](https://github.com/Genymobile/scrcpy/commit/cc0902b13c87fc98b1ed90b0700cc53ac4d7ee3c).
> 
> In fact, what I said is obsolete since [91373d9](https://github.com/Genymobile/scrcpy/commit/91373d906b100349de959f49172d4605f66f64b2).
> 
> [@Helaer](https://github.com/Helaer) Btw, could you confirm that you can run (for instance) with this diff on branch on your Samsung devices (where clipboard fails):`scrcpy --show-touches``dev`
> 

@rom1v  --show-touches works properly on scrcpy3.3.1.

**Comment by rom1v** [comment]
> --show-touches works properly on scrcpy3.3.1.

Yes, sure, but does it still work with the patch I provided?

**Comment by Helaer** [comment]
> > --show-touches 在 scrcpy3.3.1 上正常工作。
> 
> 是的，当然，但它仍然适用于我提供的补丁吗？

Sorry, I'm not a professional Android developer. I don't know how to apply this patch. Could you help me compile a server file for this patch?

**Comment by rom1v** [comment]
I just pushed it to a branch `simplify_settings`. Can you test it from there? If it's not sufficient, I'll provide a binary later.

**Comment by Helaer** [comment]
> 我只是把它推到一个分支上。您能从那里进行测试吗？如果这还不够，我稍后会提供一个二进制文件。`simplify_settings`

I see. I'm going to test this branch now.

**Comment by Helaer** [comment]
> 我只是把它推到一个分支上。您能从那里进行测试吗？如果这还不够，我稍后会提供一个二进制文件。`simplify_settings`

@rom1v  --show-touches works fine on simplify_settings, but the paste text window still crashes.

The following is the error log：

```
DEBUG: Device serial: 10.31.0.81:5555
DEBUG: Using server (portable): C:\Users\05\Desktop\scrcpy-win64-v3.3.1\scrcpy-win64-v3.3.1\scrcpy-server
C:\Users\05\Desktop\scrcpy-win64-v3.3.1\scrcpy-win6... file pushed, 0 skipped. 48.9 MB/s (90448 bytes in 0.002s)
[server] INFO: Device: [samsung] KDDI SCV42 (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
[server] DEBUG: Using video encoder: 'OMX.qcom.video.encoder.avc'
DEBUG: Using icon (portable): C:\Users\05\Desktop\scrcpy-win64-v3.3.1\scrcpy-win64-v3.3.1\icon.png
[server] DEBUG: Display: using SurfaceControl API
INFO: Renderer: direct3d
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Demuxer 'video': starting thread
INFO: Texture: 1080x1920
[server] DEBUG: Controller stopped
[server] DEBUG: Device message sender stopped
DEBUG: Demuxer 'video': end[server] ERROR: Exception on thread Thread[control-recv,5,main]
 of java.lang.SecurityException: Given calling package android does not match caller's uid 2000frames
D
E       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)BUG:
        at android.os.Parcel.createException(Parcel.java:2369)R
e       at android.os.Parcel.readException(Parcel.java:2352)c
e       at android.os.Parcel.readException(Parcel.java:2294)i
v       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6663)e
r       at android.app.ActivityThread.acquireProvider(ActivityThread.java:7643) s
t       at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3071)opp
e       at android.content.ContentResolver.acquireProvider(ContentResolver.java:2468)d

        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2758)
W       at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2920)A
R       at android.provider.Settings$System.getStringForUser(Settings.java:3404)N
:       at android.provider.Settings$System.getIntForUser(Settings.java:3503)
D       at android.provider.Settings$System.getInt(Settings.java:3497)e
v       at com.samsung.android.emergencymode.SemEmergencyManager.getModeType(SemEmergencyManager.java:343)i
c       at com.samsung.android.content.clipboard.SemClipboardManager.isUPSMode(SemClipboardManager.java:1641)e
d       at com.samsung.android.content.clipboard.SemClipboardManager.isEnabled(SemClipboardManager.java:1039)i
s       at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:132)c
o       at com.genymobile.scrcpy.wrappers.ClipboardManager.setText(ClipboardManager.java:36)n
n       at com.genymobile.scrcpy.device.Device.setClipboardText(Device.java:128)e
        at com.genymobile.scrcpy.control.Controller.setClipboard(Controller.java:595)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:306)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:219)
        at com.genymobile.scrcpy.control.Controller.lambda$start$1$com-genymobile-scrcpy-control-Controller(Controller.java:227)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9503)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2831)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3617)
        at android.os.Binder.execTransactInternal(Binder.java:1190)
        at android.os.Binder.execTransact(Binder.java:1159)

cted
DEBUG: quit...
[server] DEBUG: Screen streaming stopped
DEBUG: Controller stopped
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Comment by rom1v** [comment]
> --show-touches works fine on simplify_settings

OK, great, thank you for the test :+1: I will probably merge the change (it was not intended to fix your crash, but technically it is quite related).


Btw, what is your terminal? Is it `cmd`? The stdout/stderr from the server and from the client are interleaved quite badly.

**Comment by Helaer** [comment]
> > --show-touches 在 simplify_settings 上运行良好
> 
> 好的，太好了，谢谢你的测试👍，我可能会合并更改（它不是为了修复你的崩溃，但从技术上讲它是相当相关的）。
> 
> 顺便说一句，你的终端是什么？是吗？来自服务器和客户端的 stdout/stderr 交错得非常糟糕。`cmd`

Well, can the crash caused by pasting text be fixed?

**Comment by rom1v** [comment]
> Well, can the crash caused by pasting text be fixed?

According to @yume-chan, branch `issue6224.1` (a WIP commit I just pushed) should workaround it.

But maybe we can find a way to set the `FakeContext` as the default context more "automatically".

**Comment by Helaer** [comment]
> > 那么，粘贴文本引起的崩溃可以修复吗？
> 
> 根据 ，branch（我刚刚推送的 WIP 提交）应该可以解决这个问题。`issue6224.1`
> 
> 但也许我们可以找到一种方法来更“自动”地将 设置为 默认上下文。`FakeContext`

@rom1v  The issue6224.1 branch can indeed solve the problem of the paste text window crashing.

**Comment by Helaer** [comment]
> > Well, can the crash caused by pasting text be fixed?
> 
> According to [@yume-chan](https://github.com/yume-chan), branch `issue6224.1` (a WIP commit I just pushed) should workaround it.
> 
> But maybe we can find a way to set the `FakeContext` as the default context more "automatically".

@rom1v  Will the issue6224.1 branch be updated to the next version?

**Comment by rom1v** [comment]
In the end, it will be merged. ~But maybe when the change will be released in Android stable (not in a beta version, it sometimes changes several times during beta).~ _(I confused it with another issue)_

**Comment by rom1v** [comment]
Fixed in scrcpy 3.3.2. 🚀

**Comment by Helaer** [comment]
> 在 scrcpy 3.3.2 中修复。 🚀

Thank you!

**Comment by aliaksandrprus** [comment]
scrcpy-server: 1 file pushed, 0 skipped. 139.4 MB/s (90808 bytes in 0.001s)
[server] WARN: Audio disabled: it is not supported before Android 11
WARN: Demuxer 'audio': stream explicitly disabled by the device
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[control-recv,5,main]
java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:215)
        at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:130)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:27)
        at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:106)
        at com.genymobile.scrcpy.device.Device.setClipboardText(Device.java:119)
        at com.genymobile.scrcpy.control.Controller.setClipboard(Controller.java:595)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:306)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:219)
        at com.genymobile.scrcpy.control.Controller.lambda$start$1$com-genymobile-scrcpy-control-Controller(Controller.java:227)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(ClipboardService.java:567)
        at com.android.server.clipboard.ClipboardService.access$600(ClipboardService.java:139)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(ClipboardService.java:282)
        at android.content.IClipboard$Stub.onTransact(IClipboard.java:81)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:237)

stacktrace from 3.3.2
I get this exception every time I try to paste text on the device.
device: rooted android 9, odroid n2
bug introduced from scrcpy-win64-v3.3
I checked the latest release 3.3.2
the problem persists
previous versions worked with other exception but without device disconnecting 
([server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:142)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:189)
        at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:106)....)

**Comment by rom1v** [comment]
@aliaksandrprus

> java.lang.SecurityException: Calling uid 0 does not own package com.android.shell

Do you run adb shell as root? (is your phone rooted?) #1095

**Comment by aliaksandrprus** [comment]
yes. device rooted
 adb root
adbd is already running as root

**Comment by rom1v** [comment]
@aliaksandrprus That's the problem. For some reason, the clipboard manager throws a security exception when run as root.

Call `adb unroot` before running scrcpy.

**Comment by Helaer** [comment]
@rom1v The scrcpy_V3.3.2 window crashes again on this Android 10 device when pasting text.

log:
```
[server] INFO: Device: [Meizu] MEIZU M926Q (Android 10)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1080x1920
[server] ERROR: Exception on thread Thread[control-recv,5,main]
WARjava.lang.SecurityException: Calling uid 0 does not own package com.android.shellN
:       at android.os.Parcel.createException(Parcel.java:2071)
D       at android.os.Parcel.readException(Parcel.java:2039)ev
i       at android.os.Parcel.readException(Parcel.java:1987)c
e       at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:333)
d       at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:135)i
s       at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:27)c
o       at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:106)n
        at com.genymobile.scrcpy.device.Device.setClipboardText(Device.java:119)
n       at com.genymobile.scrcpy.control.Controller.setClipboard(Controller.java:595)e
c       at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:306)t
e       at com.genymobile.scrcpy.control.Controller.control(Controller.java:219)d

        at com.genymobile.scrcpy.control.Controller.lambda$start$1$com-genymobile-scrcpy-control-Controller(Controller.java:227)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:919)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(ClipboardService.java:688)
        at com.android.server.clipboard.ClipboardService.access$700(ClipboardService.java:157)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(ClipboardService.java:391)
        at android.content.IClipboard$Stub.onTransact(IClipboard.java:173)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:341)
``

**Comment by rom1v** [comment]
> Calling uid 0 does not own package com.android.shell

Do not run as root (call `adb unroot` before running scrcpy).

**Comment by Helaer** [comment]
> > 调用 uid 0 不拥有包 com.android.shell
> 
> 不要以 root 身份运行（在运行 scrcpy 之前调用）。`adb unroot`

@rom1v The mobile phone system has root privileges, but I didn't run adb as root. I directly started it by entering scrcpy in the cmd.This issue did not occur in Scrcpy version 3.2, and text can be pasted normally.

**Comment by rom1v** [comment]
If you run `adb shell`, how is the prompt? (what's the output?)

> This issue did not occur in Scrcpy version 3.2, and text can be pasted normally.

Can you retest scrcpy 3.2 now on the same device?

**Comment by Helaer** [comment]
> 如果你运行 ，提示如何？（输出是什么？`adb shell`
> 
> > Scrcpy 3.2 版本中没有出现此问题，文本可以正常粘贴。
> 
> 您现在可以在同一台设备上重新测试 scrcpy 3.2 吗？

@rom1v  I obtained root privileges on another new phone, When pasting, the window also crashed, It can be confirmed that adb is not running with root privileges. So as long as the mobile phone system has root privileges, pasting text will cause the window to crash. Can this problem be fixed?

**Comment by rom1v** [comment]
What's the result of `adb shell whoami`?

**Comment by Helaer** [comment]
> What's the result of ?`adb shell whoami`

log:
D:\scrcpy-win64-v3.3.2>adb shell whoami
root

**Comment by rom1v** [comment]
Call `adb unroot`, then `adb shell whoami`.

**Comment by Helaer** [comment]
> What's the result of `adb shell whoami`?

 I started scrcpy directly from the cmd.

log：
D:\scrcpy-win64-v3.3.2>adb unroot
restarting adbd as non root

D:\scrcpy-win64-v3.3.2>adb shell whoami
shell

**Comment by rom1v** [comment]
Then run scrcpy, copy-paste should work.

**Comment by Helaer** [comment]
> 然后运行 scrcpy，复制粘贴应该可以工作。



> 然后运行 scrcpy，复制粘贴应该可以工作。

@rom1v Yes, it can be pasted normally. Can't this situation be fixed? In the current version 3.3.2, as long as the phone has root permission, the window will crash when pasting,Versions 3.2 and earlier all work properly.

**Comment by Helaer** [comment]
@rom1v If you have a solution, I can test it for you.

**Comment by Helaer** [comment]
@rom1v I just conducted a detailed test,This issue has been present since Scrcpy version 3.3, and text can be pasted normally on versions 3.2 and earlier.

**Comment by Helaer** [comment]
From this branch on, a problem of the pasting text window crashing occurred on the root device.
https://github.com/Genymobile/scrcpy/pull/6129

**Comment by rom1v** [comment]
Before #6129, we passed `FakeContext.ROOT_UID` explicitly. Now that we use the standard `ClipboardManager`, we can't specify a uid. It probably fails [here](https://android.googlesource.com/platform/frameworks/base/+/android16-release/services/core/java/com/android/server/clipboard/ClipboardService.java#1324).

@yume-chan I suggest to revert 8a02e3c2f58cffc3fdd8c08b26aae04bbf9d5a97, unless there is another solution (I would prefer to keep it).  It's not totally clear to me why it worked with the previous version.

**Comment by aliaksandrprus** [comment]
why not 

try
 use clipboardManager
catch SecurityException 
 use FakeContext

?

**Comment by yume-chan** [comment]
I tested version 3.1 on a rooted Android 8 emulator:

```text
> ./scrcpy -s emulator-5554
scrcpy 3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:           (usb)  73294bba                        device  M2011K2C
INFO:     --> (tcpip)  emulator-5554                   device  Android_SDK_built_for_x86_64
C:\Users\simon\Downloads\scrcpy-win64-v3.1\scrcpy-win64-v3...file pushed, 0 skipped. 131.8 MB/s (90640 bytes in 0.001s)
[server] INFO: Device: [unknown] Android Android SDK built for x86_64 (Android 8.0.0)
[server] WARN: Audio disabled: it is not supported before Android 11
INFO: Renderer: direct3d
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 720x1280
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:142)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:189)
        at com.genymobile.scrcpy.device.Device.getClipboardText(Device.java:106)
        at com.genymobile.scrcpy.control.Controller$1.dispatchPrimaryClipChanged(Controller.java:128)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:51)
        at android.os.Binder.execTransact(Binder.java:674)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.readException(Parcel.java:1943)
        at android.os.Parcel.readException(Parcel.java:1889)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:187)
        ... 7 more
```

I don't know how it worked. It just didn't crash because the exception was caught:

https://github.com/Genymobile/scrcpy/blob/283326b2f6fa3fdaeecc181f69a3a4bcd429c06a/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L194-L197

**Comment by yume-chan** [comment]
> Or patch fields on `Workarounds.getSystemContext()` instead of creating a `ContextWrapper`, so all services are created using the patched values

Tried this idea. 

https://github.com/Genymobile/scrcpy/compare/dev...yume-chan:feat/patch-system-context?expand=1

Most things work, but `getContentResolver` can't be patched (especially for derived contexts created by `createXXXContext()`), causing 

```text
java.lang.SecurityException: Unable to find app for caller android.app.IApplicationThread$Stub$Proxy@a995e4f (pid=18959) when getting content provider settings
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6031)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7342)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2876)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2108)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2260)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2355)
        at android.provider.Settings$System.getStringForUser(Settings.java:2701)
        at android.provider.Settings$System.getIntForUser(Settings.java:2773)
        at android.provider.Settings$System.getInt(Settings.java:2767)
        at com.samsung.android.emergencymode.SemEmergencyManager.getModeType(SemEmergencyManager.java:329)
```

(ref https://github.com/Genymobile/scrcpy/issues/4639#issuecomment-2417322885)

Unless we replace [android.app.ActivityManager.IActivityManagerSingleton](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/ActivityThread.java;l=8080;drc=61197364367c9e404c7da6900658f1b16c42d0da) (used by [android.app.ActivityThread.acquireProvider](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/ActivityThread.java;l=8080;drc=61197364367c9e404c7da6900658f1b16c42d0da)) with a `Proxy`, but I think that's too dirty.

**Comment by aliaksandrprus** [comment]
For ADB to work as root, not only the device itself must be rooted, but the "rooted debugging" setting in the Developer settings must be enabled on device.
this setting may be accessed with 
https://github.com/LineageOS/android_packages_apps_Settings/blob/lineage-22.2/src/com/android/settings/development/AdbRootPreferenceController.java#L53
for example

**Comment by Helaer** [comment]
> > 然后运行 scrcpy，复制粘贴应该可以工作。
> 
> > 然后运行 scrcpy，复制粘贴应该可以工作。
> 
> [@rom1v](https://github.com/rom1v) Yes, it can be pasted normally. Can't this situation be fixed? In the current version 3.3.2, as long as the phone has root permission, the window will crash when pasting,Versions 3.2 and earlier all work properly.

@rom1v  Is there a solution to this problem now?

**Comment by yume-chan** [comment]
Google forgot to allow root to access the clipboard without an associated app. So Scrcpy must run as system (uid 1000) or shell (uid 2000) (ref #1606 and #4127)

**Comment by Helaer** [comment]
> Google forgot to allow root to access the clipboard without an associated app. So Scrcpy must run as system (uid 1000) or shell (uid 2000) (ref [#1606](https://github.com/Genymobile/scrcpy/issues/1606) and [#4127](https://github.com/Genymobile/scrcpy/pull/4127))

@yume-chan  Can this problem be fixed?

**Comment by yume-chan** [comment]
> So Scrcpy must run as system (uid 1000) or shell (uid 2000) 

Maybe drop root permission on start (until proper root support is implemented). 

```java
        try {
            Os.setuid(2000);
        } catch (Exception ignored) {
        }
```

@rom1v how do you think?

**Comment by rom1v** [comment]
> Maybe drop root permission on start (until proper root support is implemented).

Yes, that might be a solution :+1:

**Comment by rom1v** [comment]
@Helaer Please test 81b90bf58bd4f0a297f9c50ab7b35b5fdcbc9c98

Here is a binary (for scrcpy 3.3.4):
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6224/1/scrcpy-server) <sub>`SHA-256: 69d6d8f698054a68d8427bc5bf54aa26b7af17b8912308fea4a99e4cbb4e835`</sub>

**Comment by Helaer** [comment]
> [@Helaer](https://github.com/Helaer) Please test [786bbec](https://github.com/Genymobile/scrcpy/commit/786bbeca9796f2e88ee0bceb7d71d4dfa2188fa0)
> 
> Here is a binary (for scrcpy 3.3.4):
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6224/1/scrcpy-server) `SHA-256: 69d6d8f698054a68d8427bc5bf54aa26b7af17b8912308fea4a99e4cbb4e835`

Great! It can finally be pasted normally on my root device!

**Comment by Helaer** [comment]
> 请检测[81b90bf](https://github.com/Genymobile/scrcpy/commit/81b90bf58bd4f0a297f9c50ab7b35b5fdcbc9c98)
> 
> 这里有一个二进制（针对 scrcpy 3.3.4）：
> 
> * [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/6224/1/scrcpy-server) `SHA-256: 69d6d8f698054a68d8427bc5bf54aa26b7af17b8912308fea4a99e4cbb4e835`

@rom1v  I conducted tests on multiple root devices,This branch can paste text normally without the window crashing, It can finally work properly on devices with root privileges.

**Comment by rom1v** [comment]
Merged: 42632d3f53657238ca653b6f39d4226e9f0a1971
