### ISSUE TITLE
Black Desert Mobile Left Click Issue

### ISSUE THREAD

**Issue by rjbeswin** [Genymobile/scrcpy#887]
Can you please check, just played BDO Mobile, left click is not working, right click is working though.

**Comment by rom1v** [comment]
Fixed few days ago on `master`. #881

**Comment by skemayam** [comment]
hi how can i apply the fix? mine still have the same problem?

**Comment by rjbeswin** [comment]
Yes me too.

**Comment by skemayam** [comment]
> Yes me too.

if u get on how to fix this. please  share it here thanks

**Comment by rjbeswin** [comment]
nope, i tried it earlier, still not working

**Comment by rom1v** [comment]
> how can i apply the fix?

Checkout `master` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) the app.

**Comment by rjbeswin** [comment]
Hope it will be added on the pre built one scrcpy-win64-v1.10.zip. Im not capable of building the app. :<

**Comment by rom1v** [comment]
You can try this build, it (also) includes this fix: https://github.com/Genymobile/scrcpy/issues/650#issuecomment-550530774

**Comment by rjbeswin** [comment]
Thanks, it solves the Mouse issue but another problem occured. It messed up WASD buttons, its not walking/moving properly.

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/commit/532843d85649693fb0fa4b5d4c482b0f1db943de

    scrcpy --prefer-text-events=non-alpha

**Comment by rjbeswin** [comment]
Great! Do you have key mapping for this? I can only use keys such as 1 3 8
![Black Desert Mobile](https://user-images.githubusercontent.com/49226873/68366138-7f7a3580-016d-11ea-9388-8f94f05e002a.JPG)

**Comment by rom1v** [comment]
Doesn't the mkeyboard work like in v1.9?

**Comment by rjbeswin** [comment]
I think those 4 skills are working, how can i remap them though? 

1st skill = 1
2nd skill = 4
3rd skill = 8
4th skill = 9

**Comment by rjbeswin** [comment]
One more thing, im using 2 phones. 

scrcpy --prefer-text-events=non-alpha

**Comment by rom1v** [comment]
You can't remap keys in _scrcpy_ (unless you manually edit the source code).

**Comment by rjbeswin** [comment]
works with my ROG Phone 2, but its not on Huawei Mate 10. Does that vary in phone models?

**Comment by rjbeswin** [comment]
One more thing, im using 2 phones.
scrcpy --prefer-text-events=non-alpha
works with my ROG Phone 2, but its not on Huawei Mate 10. Does that vary in phone models?

**Comment by rjbeswin** [comment]
> You can't remap keys in _scrcpy_ (unless you manually edit the source code).

You mean, I need to build it right?

**Comment by rom1v** [comment]
> works with my ROG Phone 2, but its not on Huawei Mate 10. Does that vary in phone models?

It should not. In any case, with `--prefer-text-events=non-alpha`, it should behave like v1.10.

> 

> > You can't remap keys in scrcpy (unless you manually edit the source code).
> You mean, I need to build it right?

Building is the easy part. Firstly, you would need to "program" the behavior you want :)

**Comment by rjbeswin** [comment]
I'll try to check it out with my other phone. I also tried to follow some steps in building, but its too much for me right now. Im just new in this kind of things. Thank you anyways. I really love your project, hope we'll have some more features soon. Keep up the good work!

**Comment by srevinsaju** [comment]
@rjbeswin, gaming with custom keyboard remapping? Try guiscrcpy-mapper function, the GUI overlay which allows keyboard to touch custom mapping. It does not overide scrcpy, but acts as a module

https://github.com/srevinsaju/guiscrcpy

**Comment by rjbeswin** [comment]
@srevinsaju nicee, gotta try this later.
